name: craw_ppt
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.8.0
  puppeteer: ^3.9.0
  dio: ^5.4.3+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
